# Quantum Storage Daemon Configuration
network: main # dev, test, or main
mnemonic: "" # Your ThreeFold mnemonic

# Deployment configuration
meta_nodes: [11, 13, 24, 2011] # List of node IDs for metadata ZDBs
data_nodes: [11, 13, 24, 2011] # List of node IDs for data ZDBs
zdb_password: "" # Password for ZDB namespaces
meta_size_gb: 1 # Size in GB for metadata ZDBs
data_size_gb: 10 # Size in GB for data ZDBs
